[package]
name = "rust-sokoban"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = "0.25.0"
specs = { version = "0.17.0", features = ["specs-derive"] }
image = "0.24.7"